[build]
builder = "dockerfile"

[deploy]
startCommand = "app.main:app --host 0.0.0.0 --port 8080"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
